### ISSUE TITLE
Seeking Example Secrets.json

### ISSUE THREAD

**Issue by dOrgJelli** [GoodDollar/poc4#1]
Hello, I'm looking for an example Secrets.json file as I'd like to run and test this locally.

This is as far as I got reverse engineering it before I decided to just come here and ask:
```
{
  "ethereum": {
    "6000": {
      "identity": {
        "owner_pkey": "TODO"
      }
    }
  }
}
```

Thank you!

**Comment by hadarbmdev** [comment]
Hey @dOrgJelli !
Thank you for contributing. We have moved our development to this repository:
https://github.com/GoodDollar/GoodIdentity

Now are working on Express server, and are now focusing on version 0.1 which will contain Express instead of Meteor, Undux instead of Redux, and React-native instead of React. Can we chat on Telegram? I've sent you a LinkedIn message.
